In [2]:
import numpy as np
np.__version__

'1.14.2'

In [3]:
a = np.array([24, 35, 18, 40])
a

array([24, 35, 18, 40])

In [4]:
age = [24, 35, 18, 40]
age

[24, 35, 18, 40]

In [6]:
b = np.array(age)
b

array([24, 35, 18, 40])

In [7]:
b.ndim  # dimention

1

In [8]:
b.shape

(4,)

In [9]:
drink = np.array(['mocha', 'water', 'latte', 'espresso', 'coke'])
drink

array(['mocha', 'water', 'latte', 'espresso', 'coke'], dtype='<U8')

In [10]:
m = ['water', 20, 'coffe', 50]
m

['water', 20, 'coffe', 50]

In [11]:
m2 = np.array(['water', 20, 'coffe', 50])
m2

array(['water', '20', 'coffe', '50'], dtype='<U5')

In [12]:
hw = np.array([[170, 167, 159], [70, 48, 50]])
hw

array([[170, 167, 159],
       [ 70,  48,  50]])

In [13]:
hw.shape

(2, 3)

In [14]:
hw.ndim

2

In [15]:
hw.size # member

6

In [16]:
z = np.zeros((4, 2))
z

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
x = np.ones((5, 3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
k = np.zeros((4, 3))
k

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
k[:] = 9
k

array([[9., 9., 9.],
       [9., 9., 9.],
       [9., 9., 9.],
       [9., 9., 9.]])

In [20]:
e = np.identity(4)
e

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
e2 = np.eye(4)
e2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
f = np.arange(1, 11)
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
f2 = np.arange(1, 51)
f2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [25]:
f3 = np.reshape(f2, (10, 5))
f3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [27]:
f4 = np.reshape(np.arange(1, 51), (10, 5))
f4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])