In [2]:
import numpy as np
print(np.__version__)

1.14.2


In [3]:
np.random.seed(9)
x = np.random.randint(1, 11, 5)
x

array([6, 7, 9, 7, 2])

In [4]:
x * 2

array([12, 14, 18, 14,  4])

In [5]:
b = np.array([2, 2, 2, 2, 2])
b

array([2, 2, 2, 2, 2])

In [6]:
x * b

array([12, 14, 18, 14,  4])

In [7]:
x * np.array([2])

array([12, 14, 18, 14,  4])

In [8]:
np.repeat(np.array([2]), 5)

array([2, 2, 2, 2, 2])

In [9]:
x * np.repeat(np.array([2]), 5)

array([12, 14, 18, 14,  4])

In [10]:
mu = np.mean(x)
std = np.std(x)

In [11]:
mu

6.2

In [12]:
std

2.3151673805580453

In [13]:
z = (x - mu) / std
z

array([-0.08638684,  0.34554737,  1.2094158 ,  0.34554737, -1.81412369])

In [14]:
np.repeat(mu, 5)

array([6.2, 6.2, 6.2, 6.2, 6.2])

In [15]:
## 2-dim

In [16]:
a = np.arange(1, 7).reshape(3, -1)  * 10
a

array([[10, 20],
       [30, 40],
       [50, 60]])

In [17]:
a.shape

(3, 2)

In [18]:
5 + a

array([[15, 25],
       [35, 45],
       [55, 65]])

In [19]:
np.array([5]) + a

array([[15, 25],
       [35, 45],
       [55, 65]])

In [20]:
b = np.full((3, 2), 5)
b

array([[5, 5],
       [5, 5],
       [5, 5]])

In [21]:
b + a

array([[15, 25],
       [35, 45],
       [55, 65]])

In [22]:
c =  np.array([2, 10])
c

array([ 2, 10])

In [23]:
a + c

array([[12, 30],
       [32, 50],
       [52, 70]])

In [24]:
a

array([[10, 20],
       [30, 40],
       [50, 60]])

In [25]:
print(a.shape)
print(c.shape)

(3, 2)
(2,)


In [26]:
a + c

array([[12, 30],
       [32, 50],
       [52, 70]])

In [30]:
np.tile(c, a.shape[0]).reshape(a.shape) # c will change to this matrix

array([[ 2, 10],
       [ 2, 10],
       [ 2, 10]])

In [29]:
a

array([[10, 20],
       [30, 40],
       [50, 60]])

In [31]:
d = np.array([[2], [3], [4]])
d

array([[2],
       [3],
       [4]])

In [32]:
a + d

array([[12, 22],
       [33, 43],
       [54, 64]])

In [33]:
print(a.shape)
print(d.shape)

(3, 2)
(3, 1)


In [34]:
np.array([[2,2] ,[3,3], [4,4]]) # d boradcast

array([[2, 2],
       [3, 3],
       [4, 4]])

In [35]:
e = np.array([[5], [100]])
e

array([[  5],
       [100]])

In [36]:
a

array([[10, 20],
       [30, 40],
       [50, 60]])

In [37]:
print(a.shape)
print(e.shape)

(3, 2)
(2, 1)


In [ ]:
a + e # cannot boardcast