In [1]:
import numpy as np

In [3]:
a=np.arange(1, 33)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [5]:
np.random.shuffle(a) # inplace
a

array([28, 26, 30,  4,  8, 29, 27, 18, 12, 14, 20, 31,  7,  9, 15,  3, 16,
        1, 19,  5, 32, 21, 13, 17,  6, 23,  2, 25, 10, 11, 22, 24])

In [6]:
b=np.hsplit(a, 8)
b

[array([28, 26, 30,  4]),
 array([ 8, 29, 27, 18]),
 array([12, 14, 20, 31]),
 array([ 7,  9, 15,  3]),
 array([16,  1, 19,  5]),
 array([32, 21, 13, 17]),
 array([ 6, 23,  2, 25]),
 array([10, 11, 22, 24])]

In [7]:
b[0]

array([28, 26, 30,  4])

In [8]:
b[1]

array([ 8, 29, 27, 18])

In [12]:
t=np.loadtxt('worldcup2018teams.txt',dtype='U', delimiter='\n')
t

array(['Russia', 'Brazil', 'Iran', 'Japan', 'Mexico', 'Belgium',
       'South Korea', 'Saudi Arabia', 'Germany', 'England', 'Spain',
       'Nigeria', 'Costa Rica', 'Poland', 'Egypt', 'Iceland', 'Serbia',
       'Portugal', 'France', 'Uruguay', 'Argentina', 'Colombia', 'Panama',
       'Senegal', 'Morocco', 'Tunisia', 'Switzerland', 'Croatia',
       'Sweden', 'Denmark', 'Australia', 'Peru'], dtype='<U12')

In [13]:
np.random.shuffle(t)
t

array(['Egypt', 'Australia', 'Peru', 'Serbia', 'Saudi Arabia', 'Mexico',
       'Croatia', 'Morocco', 'Iran', 'Denmark', 'Uruguay', 'Switzerland',
       'Portugal', 'Russia', 'Costa Rica', 'Panama', 'Poland', 'Nigeria',
       'England', 'Belgium', 'South Korea', 'Brazil', 'Spain',
       'Argentina', 'Tunisia', 'France', 'Germany', 'Japan', 'Iceland',
       'Colombia', 'Sweden', 'Senegal'], dtype='<U12')

In [15]:
grp=np.hsplit(t, 8)
grp

[array(['Egypt', 'Australia', 'Peru', 'Serbia'], dtype='<U12'),
 array(['Saudi Arabia', 'Mexico', 'Croatia', 'Morocco'], dtype='<U12'),
 array(['Iran', 'Denmark', 'Uruguay', 'Switzerland'], dtype='<U12'),
 array(['Portugal', 'Russia', 'Costa Rica', 'Panama'], dtype='<U12'),
 array(['Poland', 'Nigeria', 'England', 'Belgium'], dtype='<U12'),
 array(['South Korea', 'Brazil', 'Spain', 'Argentina'], dtype='<U12'),
 array(['Tunisia', 'France', 'Germany', 'Japan'], dtype='<U12'),
 array(['Iceland', 'Colombia', 'Sweden', 'Senegal'], dtype='<U12')]

In [16]:
grp[0]

array(['Egypt', 'Australia', 'Peru', 'Serbia'], dtype='<U12')

In [17]:
grp[1]

array(['Saudi Arabia', 'Mexico', 'Croatia', 'Morocco'], dtype='<U12')

In [18]:
for g in grp:
    print(g)

['Egypt' 'Australia' 'Peru' 'Serbia']
['Saudi Arabia' 'Mexico' 'Croatia' 'Morocco']
['Iran' 'Denmark' 'Uruguay' 'Switzerland']
['Portugal' 'Russia' 'Costa Rica' 'Panama']
['Poland' 'Nigeria' 'England' 'Belgium']
['South Korea' 'Brazil' 'Spain' 'Argentina']
['Tunisia' 'France' 'Germany' 'Japan']
['Iceland' 'Colombia' 'Sweden' 'Senegal']


In [23]:
for i, g in enumerate(grp):
    print(chr(65+i), g)

A ['Egypt' 'Australia' 'Peru' 'Serbia']
B ['Saudi Arabia' 'Mexico' 'Croatia' 'Morocco']
C ['Iran' 'Denmark' 'Uruguay' 'Switzerland']
D ['Portugal' 'Russia' 'Costa Rica' 'Panama']
E ['Poland' 'Nigeria' 'England' 'Belgium']
F ['South Korea' 'Brazil' 'Spain' 'Argentina']
G ['Tunisia' 'France' 'Germany' 'Japan']
H ['Iceland' 'Colombia' 'Sweden' 'Senegal']


In [25]:
np.random.choice(grp[1], size=2, replace=False)

array(['Mexico', 'Morocco'], dtype='<U12')

In [26]:
for g in grp:
    print(np.random.choice(g, size=2, replace=False))

['Australia' 'Serbia']
['Morocco' 'Croatia']
['Iran' 'Switzerland']
['Panama' 'Costa Rica']
['Belgium' 'Nigeria']
['Brazil' 'Spain']
['Tunisia' 'Japan']
['Sweden' 'Senegal']


In [27]:
for i, g in enumerate(grp):
    print(chr(65+i), np.random.choice(g, size=2, replace=False))

A ['Egypt' 'Serbia']
B ['Morocco' 'Croatia']
C ['Uruguay' 'Switzerland']
D ['Panama' 'Russia']
E ['England' 'Poland']
F ['Argentina' 'South Korea']
G ['Tunisia' 'Germany']
H ['Colombia' 'Senegal']
