In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.14.2


In [3]:
a = np.arange(10) * 10
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [4]:
for n in a:
    print(n)

0
10
20
30
40
50
60
70
80
90


In [7]:
for i, v in enumerate(a):
    print(i, v)

0 0
1 10
2 20
3 30
4 40
5 50
6 60
7 70
8 80
9 90


In [8]:
for i, v in enumerate(a, start = 1):
    print(i, v)

1 0
2 10
3 20
4 30
5 40
6 50
7 60
8 70
9 80
10 90


# 2-dim array

In [9]:
b = np.arange(1, 21).reshape(4, 5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [10]:
for r in b:
    print(r)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]
[16 17 18 19 20]


In [11]:
for n in b.flat:
    print(n)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [13]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [12]:
for i, v in np.ndenumerate(b):
    print(i, v)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(1, 0) 6
(1, 1) 7
(1, 2) 8
(1, 3) 9
(1, 4) 10
(2, 0) 11
(2, 1) 12
(2, 2) 13
(2, 3) 14
(2, 4) 15
(3, 0) 16
(3, 1) 17
(3, 2) 18
(3, 3) 19
(3, 4) 20


In [15]:
for i, v in np.ndenumerate(b[1]):
    print(i, v)

(0,) 6
(1,) 7
(2,) 8
(3,) 9
(4,) 10


In [16]:
for i, v in np.ndenumerate(b[1:4]):
    print(i, v)

(0, 0) 6
(0, 1) 7
(0, 2) 8
(0, 3) 9
(0, 4) 10
(1, 0) 11
(1, 1) 12
(1, 2) 13
(1, 3) 14
(1, 4) 15
(2, 0) 16
(2, 1) 17
(2, 2) 18
(2, 3) 19
(2, 4) 20


In [17]:
for i, v in np.ndenumerate(b[:, 2]):
    print(i, v)

(0,) 3
(1,) 8
(2,) 13
(3,) 18


In [18]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [19]:
for n in b.flat:
    print(n)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


# 3-dim array

In [20]:
c = np.arange(1, 31).reshape(3, 2, 5)
c

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

In [21]:
c[0]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [22]:
c[0][1]

array([ 6,  7,  8,  9, 10])

In [23]:
for n in c.flat:
    print(n)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30


In [25]:
c

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

In [24]:
for i, v in np.ndenumerate(c):
    print(i, v)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 5
(0, 1, 0) 6
(0, 1, 1) 7
(0, 1, 2) 8
(0, 1, 3) 9
(0, 1, 4) 10
(1, 0, 0) 11
(1, 0, 1) 12
(1, 0, 2) 13
(1, 0, 3) 14
(1, 0, 4) 15
(1, 1, 0) 16
(1, 1, 1) 17
(1, 1, 2) 18
(1, 1, 3) 19
(1, 1, 4) 20
(2, 0, 0) 21
(2, 0, 1) 22
(2, 0, 2) 23
(2, 0, 3) 24
(2, 0, 4) 25
(2, 1, 0) 26
(2, 1, 1) 27
(2, 1, 2) 28
(2, 1, 3) 29
(2, 1, 4) 30
