In [1]:
import numpy as np

In [3]:
a = np.random.randint(0, 100, 20)
a

array([36, 38, 21,  6, 10, 76, 68, 41, 40, 23, 47, 13, 30,  0, 91, 83, 42,
       73, 22, 31])

In [5]:
a % 2 == 0

array([ True,  True, False,  True,  True,  True,  True, False,  True,
       False, False, False,  True,  True, False, False,  True, False,
        True, False])

In [6]:
a[a % 2 == 0]

array([36, 38,  6, 10, 76, 68, 40, 30,  0, 42, 22])

In [7]:
(a % 2 == 0) & (a > 50)

array([False, False, False, False, False,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [8]:
a[(a % 2 == 0) & (a > 50)]

array([76, 68])

In [9]:
a[(a % 2 == 0) | (a > 50)]

array([36, 38,  6, 10, 76, 68, 40, 30,  0, 91, 83, 42, 73, 22])

In [10]:
p = np.random.randint(1, 9999, 100)
p

array([2148, 7963,   93,  824, 6232, 6341, 8752, 7179, 6046,  393, 1437,
        804, 2079, 5966, 1487, 5718, 2363, 2775, 4183, 2222, 4344,  873,
        191, 8516, 5430, 6562, 6611, 5304, 1498,  729, 4269, 7027, 4426,
       4330, 7075, 3846, 4066, 4677, 8659, 4808, 9370, 2288, 6275, 2182,
       2151, 6410, 8607, 6960, 9228, 6950, 7703, 9031, 2049, 4580, 9407,
       5259, 6470, 9633, 8262, 5516, 6144, 5047, 9223, 2538, 6761, 7228,
       4815, 2567, 2662, 3355,  794, 7346, 4109, 4886, 1674, 7368, 1487,
       1300, 9752, 1789, 9030, 4845, 2538, 8322,    1, 7937, 7065,   10,
       9734, 5085,  382, 6687, 2141, 6016, 9276, 7196, 7234, 8332, 3433,
       3157])

In [11]:
p % 10 == 9

array([False, False, False, False, False, False, False,  True, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True,  True, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [12]:
p[p % 10 == 9]

array([7179, 2079,  729, 4269, 8659, 2049, 5259, 4109, 1789])

In [15]:
np.where(p % 10 == 9)

(array([ 7, 12, 29, 30, 38, 52, 55, 72, 79]),)

In [16]:
p[np.where(p % 10 == 9)]

array([7179, 2079,  729, 4269, 8659, 2049, 5259, 4109, 1789])