In [1]:
import numpy as np
print(np.__version__)

1.14.2


In [5]:
a = np.arange(1, 13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
a.reshape(4, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [7]:
a.reshape(4, -1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [8]:
a.reshape(-1, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
a.reshape(-1, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [10]:
b = a.reshape(-1, 2)
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [11]:
b.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [12]:
b.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# tile

In [13]:
d = np.array([2, 1, 8])
d

array([2, 1, 8])

In [14]:
np.tile(d, 3)

array([2, 1, 8, 2, 1, 8, 2, 1, 8])

In [15]:
np.tile(d, (3, 1))

array([[2, 1, 8],
       [2, 1, 8],
       [2, 1, 8]])

In [17]:
e = np.array([[1, 2], [10, 20]])
e

array([[ 1,  2],
       [10, 20]])

In [18]:
np.tile(e, 3)

array([[ 1,  2,  1,  2,  1,  2],
       [10, 20, 10, 20, 10, 20]])

In [19]:
np.tile(e, (5 ,1))

array([[ 1,  2],
       [10, 20],
       [ 1,  2],
       [10, 20],
       [ 1,  2],
       [10, 20],
       [ 1,  2],
       [10, 20],
       [ 1,  2],
       [10, 20]])

In [20]:
np.tile(e, (5 ,2))

array([[ 1,  2,  1,  2],
       [10, 20, 10, 20],
       [ 1,  2,  1,  2],
       [10, 20, 10, 20],
       [ 1,  2,  1,  2],
       [10, 20, 10, 20],
       [ 1,  2,  1,  2],
       [10, 20, 10, 20],
       [ 1,  2,  1,  2],
       [10, 20, 10, 20]])

In [21]:
np.tile([[4, 7], [8, 9]], (4, 3))

array([[4, 7, 4, 7, 4, 7],
       [8, 9, 8, 9, 8, 9],
       [4, 7, 4, 7, 4, 7],
       [8, 9, 8, 9, 8, 9],
       [4, 7, 4, 7, 4, 7],
       [8, 9, 8, 9, 8, 9],
       [4, 7, 4, 7, 4, 7],
       [8, 9, 8, 9, 8, 9]])

In [22]:
np.tile([1, 0], 4)

array([1, 0, 1, 0, 1, 0, 1, 0])

In [23]:
np.tile([[1, 0], [0 ,1]], (4, 4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

# repeat

In [24]:
np.repeat(9, 3)

array([9, 9, 9])

In [25]:
np.repeat([10, 15, 20], 2)

array([10, 10, 15, 15, 20, 20])

In [ ]:
g = np.array([[]])