In [1]:
import numpy as np

In [2]:
team=np.arange(1, 11)
team

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.random.shuffle(team)
team

array([ 6,  2,  5,  4, 10,  3,  9,  8,  7,  1])

In [10]:
training, test = team[:7], team[7:]
print(training)
print(test)

[ 6  2  5  4 10  3  9]
[8 7 1]


In [12]:
d=np.random.randint(100, 400, size=(10, 4))
d

array([[273, 241, 120, 341],
       [163, 374, 301, 110],
       [183, 267, 123, 221],
       [269, 316, 321, 303],
       [292, 249, 174, 175],
       [130, 287, 165, 229],
       [179, 190, 293, 357],
       [269, 223, 284, 394],
       [383, 197, 264, 236],
       [291, 260, 284, 104]])

In [13]:
np.random.shuffle(d)
d

array([[183, 267, 123, 221],
       [269, 223, 284, 394],
       [383, 197, 264, 236],
       [291, 260, 284, 104],
       [273, 241, 120, 341],
       [292, 249, 174, 175],
       [269, 316, 321, 303],
       [130, 287, 165, 229],
       [179, 190, 293, 357],
       [163, 374, 301, 110]])

In [14]:
training, test = d[:7], d[7:]
training

array([[183, 267, 123, 221],
       [269, 223, 284, 394],
       [383, 197, 264, 236],
       [291, 260, 284, 104],
       [273, 241, 120, 341],
       [292, 249, 174, 175],
       [269, 316, 321, 303]])

In [15]:
test

array([[130, 287, 165, 229],
       [179, 190, 293, 357],
       [163, 374, 301, 110]])

# method 2

In [16]:
d=np.random.randint(100, 400, size=(10, 4))
d

array([[131, 362, 247, 283],
       [354, 285, 153, 262],
       [180, 394, 315, 148],
       [186, 388, 290, 285],
       [338, 145, 361, 375],
       [388, 222, 166, 179],
       [301, 321, 121, 381],
       [262, 395, 204, 357],
       [222, 248, 343, 121],
       [252, 303, 387, 215]])

In [19]:
r1 = np.random.choice(np.arange(d.shape[0]), size=7, replace=False)
r1

array([2, 7, 4, 6, 8, 0, 9])

In [20]:
training=d[r1]
training

array([[180, 394, 315, 148],
       [262, 395, 204, 357],
       [338, 145, 361, 375],
       [301, 321, 121, 381],
       [222, 248, 343, 121],
       [131, 362, 247, 283],
       [252, 303, 387, 215]])

In [21]:
np.setdiff1d(np.arange(d.shape[0]), r1)

array([1, 3, 5])

In [22]:
test=d[np.setdiff1d(np.arange(d.shape[0]), r1)]
test

array([[354, 285, 153, 262],
       [186, 388, 290, 285],
       [388, 222, 166, 179]])